-- Seed categories + 15 products (FRP doors, locks, door parts)
-- Run in Supabase SQL editor after schema.sql / sales_invoice.sql

alter table public.products
  add column if not exists unit text default 'Nos';

alter table public.products
  add column if not exists brand text;

insert into public.product_categories (name)
values
  ('FRP Doors'),
  ('Accessories'),
  ('Glass'),
  ('Locks')
on conflict (name) do nothing;

insert into public.products (
  name,
  product_code,
  category_id,
  size,
  material,
  colour,
  hsn_code,
  unit,
  brand,
  gst_rate,
  mrp,
  selling_price,
  dealer_price,
  stock_quantity,
  minimum_stock
)
values
  (
    'FRP Door (White)',
    'PD-001',
    (select id from public.product_categories where name = 'FRP Doors'),
    '30" x 80"',
    'FRP',
    'White',
    '392520',
    'Nos',
    'Sanro',
    18,
    12500,
    11200,
    9800,
    42,
    10
  ),
  (
    'FRP Door (Brown)',
    'PD-002',
    (select id from public.product_categories where name = 'FRP Doors'),
    '30" x 80"',
    'FRP',
    'Brown',
    '392520',
    'Nos',
    'Sanro',
    18,
    12800,
    11500,
    10000,
    28,
    8
  ),
  (
    'FRP Door (Designer Panel)',
    'PD-003',
    (select id from public.product_categories where name = 'FRP Doors'),
    '32" x 84"',
    'FRP',
    'Teak',
    '392520',
    'Nos',
    'Sanro',
    18,
    16500,
    14800,
    12900,
    12,
    5
  ),
  (
    'Door Frame (6ft)',
    'PD-004',
    (select id from public.product_categories where name = 'Accessories'),
    '6 ft',
    'FRP',
    'White',
    '392590',
    'Nos',
    'Sanro',
    18,
    3200,
    2850,
    2400,
    65,
    15
  ),
  (
    'Door Handle (SS)',
    'PD-005',
    (select id from public.product_categories where name = 'Accessories'),
    'Standard',
    'Stainless Steel',
    'Silver',
    '830241',
    'Nos',
    'Ebco',
    18,
    450,
    380,
    290,
    180,
    40
  ),
  (
    'Door Hinge (4 inch)',
    'PD-006',
    (select id from public.product_categories where name = 'Accessories'),
    '4 inch',
    'SS',
    'Silver',
    '830210',
    'Nos',
    'Ebco',
    18,
    85,
    65,
    48,
    320,
    50
  ),
  (
    'Mortise Lock',
    'PD-007',
    (select id from public.product_categories where name = 'Locks'),
    'Standard',
    'Zinc Alloy',
    'Satin',
    '830160',
    'Nos',
    'Godrej',
    18,
    1850,
    1620,
    1380,
    54,
    12
  ),
  (
    'Cylinder Lock',
    'PD-008',
    (select id from public.product_categories where name = 'Locks'),
    '70mm',
    'Brass',
    'Chrome',
    '830140',
    'Nos',
    'Yale',
    18,
    2200,
    1950,
    1680,
    36,
    10
  ),
  (
    'Deadbolt Lock',
    'PD-009',
    (select id from public.product_categories where name = 'Locks'),
    'Single',
    'Steel',
    'Black',
    '830140',
    'Nos',
    'Godrej',
    18,
    1450,
    1280,
    1090,
    8,
    10
  ),
  (
    'Night Latch Lock',
    'PD-010',
    (select id from public.product_categories where name = 'Locks'),
    'Standard',
    'Zinc',
    'Silver',
    '830140',
    'Nos',
    'Godrej',
    18,
    980,
    850,
    720,
    0,
    8
  ),
  (
    'Rubber Seal Strip',
    'PD-011',
    (select id from public.product_categories where name = 'Accessories'),
    '12mm',
    'EPDM Rubber',
    'Black',
    '401693',
    'Meter',
    'Local',
    18,
    45,
    38,
    28,
    240,
    50
  ),
  (
    'Door Closer (Hydraulic)',
    'PD-012',
    (select id from public.product_categories where name = 'Accessories'),
    'Medium duty',
    'Aluminium',
    'Silver',
    '830260',
    'Nos',
    'Dorma',
    18,
    1650,
    1420,
    1180,
    22,
    6
  ),
  (
    'Tower Bolt (SS)',
    'PD-013',
    (select id from public.product_categories where name = 'Accessories'),
    '6 inch',
    'Stainless Steel',
    'Silver',
    '830241',
    'Nos',
    'Ebco',
    18,
    120,
    95,
    72,
    150,
    30
  ),
  (
    'Aldrop (Brass)',
    'PD-014',
    (select id from public.product_categories where name = 'Accessories'),
    '10 inch',
    'Brass',
    'Antique',
    '830241',
    'Nos',
    'Local',
    18,
    380,
    320,
    250,
    5,
    10
  ),
  (
    'Glass Panel (Clear)',
    'PD-015',
    (select id from public.product_categories where name = 'Glass'),
    '5mm',
    'Float Glass',
    'Clear',
    '700719',
    'Sq.Ft',
    'Saint-Gobain',
    18,
    95,
    82,
    68,
    410,
    80
  )
on conflict (product_code) do update set
  name = excluded.name,
  category_id = excluded.category_id,
  size = excluded.size,
  material = excluded.material,
  colour = excluded.colour,
  hsn_code = excluded.hsn_code,
  unit = excluded.unit,
  brand = excluded.brand,
  gst_rate = excluded.gst_rate,
  mrp = excluded.mrp,
  selling_price = excluded.selling_price,
  dealer_price = excluded.dealer_price,
  stock_quantity = excluded.stock_quantity,
  minimum_stock = excluded.minimum_stock,
  updated_at = now();
